export const courseOne = {
    id: 'data-science1',
    imageUrl: "/images/common/1.jpg",
    title: "The Complete Python boot camp from zero to hero in just a few months.",
    instructor: "Dr. Angela Yu, Developer and Leader of the community",
    rating: 5,
    totalRatings: "42,329",
    price: "99.99",
    originalPrice: "149.99",
    bestseller: true,
    href: "/"
}

export const courseTwo = {
    id: 'data-science1',
    imageUrl: "/images/common/2.jpg",
    title: "The Complete Python boot camp from zero to hero in just a few months.",
    instructor: "Dr. Angela Yu, Developer and Leader of the community",
    rating: 5,
    totalRatings: "42,329",
    price: "99.99",
    originalPrice: "149.99",
    bestseller: true,
    href: "/"
}

export const datas = [
    {
        category: "Data Science",
        title: "Enhance Your Skills in Data Science",
        subTitle: "Learn to extract insights from data and make informed decisions.",
        href: "/",
        items: [
            {
                id: 'data-science1',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'data-science2',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'data-science3',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'data-science4',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'data-science5',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'data-science6',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'data-science7',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'data-science8',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'data-science9',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'data-science10',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'data-science11',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'data-science12',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
        ],
    },
    {
        category: "Digital Marketing",
        title: "Master the Art of Digital Marketing",
        subTitle: "Boost your brand's online presence with cutting-edge marketing strategies.",
        href: "/",
        items: [
            {
                id: 'digital-marketing1',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'digital-marketing2',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'digital-marketing3',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'digital-marketing4',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'digital-marketing5',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'digital-marketing6',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'digital-marketing7',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'digital-marketing8',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'digital-marketing9',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'digital-marketing10',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'digital-marketing11',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'digital-marketing12',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
        ],
    },
    {
        category: "Graphic Design",
        title: "Explore Your Creativity with Graphic Design",
        subTitle: "Turn your ideas into stunning visual content.",
        href: "/",
        items: [
            {
                id: 'graphic-designing1',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'graphic-designing2',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'graphic-designing3',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'graphic-designing4',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'graphic-designing5',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'graphic-designing6',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'graphic-designing7',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'graphic-designing8',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'graphic-designing9',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'graphic-designing10',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'graphic-designing11',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'graphic-designing12',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
        ],
    },
    {
        category: "Cybersecurity",
        title: "Protect Your Digital Assets with Cybersecurity",
        subTitle: "Learn how to safeguard your information and systems from threats.",
        href: "/",
        items: [
            {
                id: 'cybersecurity1',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'cybersecurity2',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'cybersecurity3',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'cybersecurity4',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'cybersecurity5',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'cybersecurity6',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'cybersecurity7',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'cybersecurity8',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'cybersecurity9',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'cybersecurity10',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'cybersecurity11',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'cybersecurity12',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
        ],
    },
    {
        category: "Artificial Intelligence",
        title: "Unlock the Power of AI",
        subTitle: "Dive into the world of machine learning and intelligent systems.",
        href: "/",
        items: [
            {
                id: 'ai1',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'ai2',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'ai3',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'ai4',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'ai5',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'ai6',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'ai7',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'ai8',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'ai9',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'ai10',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'ai11',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: 'ai12',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
        ],
    },
]