export const courseOne = {
    id: '1',
    imageUrl: "/images/common/1.jpg",
    title: "The Complete Python boot camp from zero to hero in just a few months.",
    instructor: "Dr. Angela Yu, Developer and Leader of the community",
    rating: 5,
    totalRatings: "42,329",
    price: "99.99",
    originalPrice: "149.99",
    bestseller: true,
    href: "/"
}

export const courseTwo = {
    id: '1',
    imageUrl: "/images/common/2.jpg",
    title: "The Complete Python boot camp from zero to hero in just a few months.",
    instructor: "Dr. Angela Yu, Developer and Leader of the community",
    rating: 5,
    totalRatings: "42,329",
    price: "99.99",
    originalPrice: "149.99",
    bestseller: true,
    href: "/"
}

export const datas = [
    {
        category: "Data Science",
        title: "Enhance Your Skills in Data Science",
        subTitle: "Learn to extract insights from data and make informed decisions.",
        href: "/",
        items: [
            {
                id: '1',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '2',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '3',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '4',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '5',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '6',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '7',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '8',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '9',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '10',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '11',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '12',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
        ],
    },
    {
        category: "Digital Marketing",
        title: "Master the Art of Digital Marketing",
        subTitle: "Boost your brand's online presence with cutting-edge marketing strategies.",
        href: "/",
        items: [
            {
                id: '1',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '2',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '3',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '4',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '5',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '6',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '7',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '8',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '9',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '10',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '11',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '12',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
        ],
    },
    {
        category: "Graphic Design",
        title: "Explore Your Creativity with Graphic Design",
        subTitle: "Turn your ideas into stunning visual content.",
        href: "/",
        items: [
            {
                id: '1',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '2',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '3',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '4',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '5',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '6',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '7',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '8',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '9',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '10',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '11',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '12',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
        ],
    },
    {
        category: "Cybersecurity",
        title: "Protect Your Digital Assets with Cybersecurity",
        subTitle: "Learn how to safeguard your information and systems from threats.",
        href: "/",
        items: [
            {
                id: '1',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '2',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '3',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '4',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '5',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '6',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '7',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '8',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '9',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '10',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '11',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '12',
                imageUrl: "/images/common/2.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
        ],
    },
    {
        category: "Artificial Intelligence",
        title: "Unlock the Power of AI",
        subTitle: "Dive into the world of machine learning and intelligent systems.",
        href: "/",
        items: [
            {
                id: '1',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '2',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '3',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '4',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '5',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '6',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '7',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '8',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '9',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '10',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '11',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
            {
                id: '12',
                imageUrl: "/images/common/1.jpg",
                title: "The Complete Python boot camp from zero to hero in just a few months.",
                instructor: "Dr. Angela Yu, Developer and Leader of the community",
                rating: 5,
                totalRatings: "42,329",
                price: "99.99",
                originalPrice: "149.99",
                bestseller: true,
                href: "/"
            },
        ],
    },
]
